### ISSUE TITLE
Failed to allocate a 889612 byte allocation with 867288 free bytes and 846KB until OOM

### ISSUE THREAD

**Issue by huss22us** [ai212983/android-spinnerwheel#64]
I am using this library to show some numbers and some text only.

sometime I got crash reports -- that the library crashed at function called recreateAssets.
I don't use any drawings or images with this library.

here is the log for the crash

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 889612 byte allocation with 867288 free bytes and 846KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:942)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
       at antistatic.spinnerwheel.AbstractWheelView.recreateAssets(AbstractWheelView.java:188)
       at antistatic.spinnerwheel.AbstractWheel.onLayout(AbstractWheel.java:445)
       at android.view.View.layout(View.java:16942)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1691)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1467)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16942)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2452)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2156)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1297)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6991)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by ai212983** [comment]
This library is using bitmaps to draw on canvas, even with text.
Do you still have this problem?

**Comment by huss22us** [comment]
Yes , I have an application which uses the library heavily -- hope this could be fixed soon
